# Generated by Django 5.1.2 on 2024-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatingroom',
            name='pdf_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
