# Generated by Django 5.1.2 on 2024-10-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0002_chatingroom_pdf_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chating',
            name='chatingRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chating', to='chating.chatingroom'),
        ),
    ]
