# Generated by Django 5.1.2 on 2024-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chating", "0003_alter_chating_chatingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatingroom",
            name="title",
            field=models.CharField(default="(Chatting Room Title)", max_length=30),
        ),
    ]
