# Generated by Django 5.1.2 on 2024-10-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0004_chatingroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatingroom',
            name='pdf_embedding',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
