# Generated by Django 5.1.2 on 2024-10-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chating", "0005_alter_chatingroom_pdf_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="chating",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chating",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chating",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chating",
            name="total_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
