# Generated by Django 5.1.2 on 2024-10-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailvalidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
